GET http://localhost:3000/users

###
GET http://localhost:3000/users/2



###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Agun",
    "email" : "Agunnnnnn@gmail.com",
    "gender" : "Male"
    

}

###
PATCH  http://localhost:3000/users/2
Content-Type: application/json

{
    "name" : "Reno",
    "email" : "Reno@gmail.com",
    "gender" : "Male"
    

}

###
PATCH  http://localhost:3000/users/6
Content-Type: application/json

{
    "name" : "Agun",
    "email" : "Agun@gmail.com",
    "gender" : "Male"
    

}

###
DELETE http://localhost:3000/users/2